version: "3"
services:
  backend:
    image: hardikg2907/nft-marketplace-backend-1.0.0
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8545:8545"
  frontend:
    image: hardikg2907/nft-marketplace-frontend-1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
